name: Kip Russel
favicon: null
layout_spectrum: 0.97168
typography_spectrum: 0.50293
title: "Denver's most versatile, tech-savvy and personable male escort"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59801585-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#454545'
    - '#1b1b1b'
    - '#9f9f9f'
    - '#5ceaee'
    - '#f0e7ba'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
