name: Kip Russel
favicon: null
layout_spectrum: 0.04004
typography_spectrum: 0.50293
title: "Denver's most versatile, tech-savvy and personable male escort"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59801585-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb69b'
    - '#191516'
    - '#654b4e'
    - '#a47a74'
    - '#fee6c2'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
